### ISSUE TITLE
Form Validation Error Message

### ISSUE THREAD

**Issue by cammac60** [JamesRexMiller4/swapi_trivia#22]
The form validation error message does not go away when all information is entered. We may want to consider changing this.

**Comment by JamesRexMiller4** [comment]
Yes I agree, I am wondering how we could accomplish it. I think it would require state to be updated using onChange, or maybe OnBlue when the user clicks out of the input. Maybe we can create a separate method in the Form component to evaluate this and keep this in its state? What do you think?

**Comment by cammac60** [comment]
@JamesRexMiller4 I think this could work. We could add it to our on change function and just say if (all fields have a value) toggle the error classname so that it's hidden.
